// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvqzeomzuplkdlvkvbee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2cXplb216dXBsa2Rsdmt2YmVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNDU1NTcsImV4cCI6MjA2NDYyMTU1N30.W54Dp8kvhkL88-7ZjQH7O7U_YqErKGAJudeK0EW5NSE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);